### PR TITLE
Update workshops

### PR DESCRIPTION
**Pull request by k4rni**
- [x] Update spring2024 workshops
- [x] Add fall2023 workshops

image
image
image

### CODE REVIEW

**Comment by k4rni** [comment]
@EthanThatOneKid Should the workshop folders be in order? Currently it is alphabetical, but should it based on year?

**Comment by EthanThatOneKid** [comment]
> @EthanThatOneKid Should the workshop folders be in order? Currently it is alphabetical, but should it based on year?

We could sort it based on the timestamp of the first workshop in the series.

**Review by EthanThatOneKid — APPROVED** [review]
> > @EthanThatOneKid Should the workshop folders be in order? Currently it is alphabetical, but should it based on year?
> 
> We could sort it based on the timestamp of the first workshop in the series.

Resolved in <https://github.com/acmcsufoss/docs/pull/2/commits/2748d2f8b0eb56cbd95050c09b8994c80a4481b2> 😎 cc @karnikaavelumani

**Comment by EthanThatOneKid** [comment]
@karnikaavelumani Thank you for volunteering to do this task :)

**Comment by k4rni** [comment]
Thank you for fixing the change I asked! ☺️

**Pull request merged**
